header = "// SPDX-License-Identifier: MIT OR Apache-2.0"
includes = ["rice-proto.h"]
include_guard = "LIBRICE_IO_H"
tab_width = 4
language = "C"
cpp_compat = true
usize_is_size_t = true

[export]
exclude = ["MAGIC_COOKIE", "BINDING", "RTP", "RTCP"]
item_types = ["enums", "structs", "opaque", "functions", "typedefs"]

[export.rename]
"CandidateType" = "RiceCandidateType"
"ComponentConnectionState" = "RiceComponentConnectionState"

[fn]
args = "vertical"

[enum]
rename_variants = "QualifiedScreamingSnakeCase"
