[graph]
all-features = false
no-default-features = false
exclude-unpublished = true

[advisories]
db-urls = ["https://github.com/rustsec/advisory-db"]

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "Unicode-3.0",
    "ISC",
    "OpenSSL",
    "Zlib",
]
confidence-threshold = 0.9

[bans]
multiple-versions = "deny"
wildcards = "allow"
highlight = "all"
skip-tree = [
    # FIXME: replace get_if_addrs
    { crate = "get_if_addrs", reason = "Outdated dependency that needs replacing" },
    { crate = "bindgen", reason = "Build dependency only" },
    { crate = "windows-sys@0.59", reason = "a foundational crate for many that bumps far too frequently to ever have a shared version" },
    { crate = "windows-sys@0.60", reason = "a foundational crate for many that bumps far too frequently to ever have a shared version" },
    { crate = "getrandom@0.2", reason = "flume depends on an old version of getrandom" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
