[package]
name = "librice-proto"
description = "ICE (RFC8445) implementation protocol"
version = "0.0.3"
authors = ["Matthew Waters <matthew@centricular.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"
keywords = ["STUN", "ICE"]
categories = ["network-programming", ]
documentation = "https://docs.rs/librice"
repository = "https://github.com/ystreet/librice"
workspace = ".."

[dependencies]
arbitrary = { version = "1", optional = true, features = ["derive"] }
byteorder = "1"
rand = "0.8"
crc = "3"
sha-1 = "0.10"
sha2 = "0.10"
md-5 = "0.10"
hmac = "0.12"
tracing = { version = "0.1", features = ["log"] }
nom = "7"

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["std", "env-filter"] }
