[package]
name = "librice-proto"
description = "ICE (RFC8445) implementation protocol"
version.workspace = true
authors = ["Matthew Waters <matthew@centricular.com>"]
license = "MIT OR Apache-2.0"
keywords = ["STUN", "ICE"]
categories = ["network-programming", ]
documentation = "https://docs.rs/librice-proto"
edition.workspace = true
repository.workspace = true
rust-version.workspace = true
workspace = ".."

[dependencies]
arbitrary = { workspace = true, optional = true }
byteorder.workspace = true
crc = "3"
hmac = "0.12"
md-5 = "0.10"
nom = "7"
rand.workspace = true
sha-1 = "0.10"
sha2 = "0.10"
tracing.workspace = true

[dev-dependencies]
tracing-subscriber.workspace = true
