header = "// SPDX-License-Identifier: MIT OR Apache-2.0"
includes = []
include_guard = "LIBRICE_PROTO_H"
tab_width = 4
language = "C"
cpp_compat = true
usize_is_size_t = true

[export]
exclude = ["MAGIC_COOKIE", "BINDING", "RTP", "RTCP"]
item_types = ["enums", "structs", "opaque", "functions"]

[export.rename]
#"sockaddr" = "struct sockaddr"
#"sockaddr_storage" = "struct sockaddr_storage"
"CandidateType" = "RiceCandidateType"
"ComponentConnectionState" = "RiceComponentConnectionState"

[fn]
args = "vertical"

[enum]
rename_variants = "QualifiedScreamingSnakeCase"
