on: [push]

name: Code Coverage

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cargo-tarpaulin
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: '--version 0.23.1 cargo-tarpaulin'

      - name: Run cargo-tarpaulin
        uses: actions-rs/cargo@v1
        with:
          command: 'tarpaulin'
          args: '--out Xml -- --test-threads 1'

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{secrets.CODECOV_TOKEN}}

      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: cobertura.xml
