name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Install cargo-tarpaulin
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: cargo-tarpaulin@0.32

      - name: Install cargo-c
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: cargo-c

      - name: Run cargo-tarpaulin
        uses: actions-rs/cargo@v1
        with:
          command: 'tarpaulin'
          args: '--out Xml --lib --tests --doc -- --test-threads 1'

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v5
        with:
          token: ${{secrets.CODECOV_TOKEN}}

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: cobertura.xml
