name: Rust docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTDOCFLAGS: -Dwarnings

jobs:
  cargo_doc:
    name: Cargo doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install cargo-c
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: cargo-c
      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps

  cargo_docs_rs:
    name: Cargo docs-rs
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -Dwarnings
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Install cargo-c
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: cargo-c
      - name: Install cargo-docs-rs
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: cargo-docs-rs
      - run: for p in librice rice-proto rice-ctypes rice-stun-types rice-c rice-io; do echo $p; cargo +nightly docs-rs -v -p $p; done
