name: Quick Fuzzing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  fuzz:
    name: Fuzzing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Install cargo-fuzz
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: cargo-fuzz

      - name: Run cargo-fuzz
        uses: actions-rs/cargo@v1
        with:
          command: 'fuzz'
          args: 'run parse_candidate -- -max_total_time=20'

